"use client";

import "@fontsource/noto-sans-jp/400.css";
import "@fontsource/noto-sans-jp/500.css";
import "@fontsource/noto-sans-jp/700.css";

export const textStyles = {
  largeText: {
    fontSize: "32px",
    fontWeight: 700,
    lineHeight: 1.5,
    letterSpacing: "0.04em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  h1: {
    fontSize: "26px",
    fontWeight: 700,
    lineHeight: 1.5,
    letterSpacing: "0.04em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  h2: {
    fontSize: "24px",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: "0em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  h3: {
    fontSize: "22px",
    fontWeight: 700,
    lineHeight: 1.5,
    letterSpacing: "0.04em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  h4: {
    fontSize: "20px",
    fontWeight: 700,
    lineHeight: 1.5,
    letterSpacing: "0.04em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  h5: {
    fontSize: "18px",
    fontWeight: 700,
    lineHeight: 1.5,
    letterSpacing: "0.04em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  h6: {
    fontFamily: "Noto Sans JP, sans-serif",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "150%" /* 24px */,
    letterSpacing: "0.64px",
  },
  button: {
    fontSize: "16px",
    fontWeight: 700,
    lineHeight: 1.5,
    letterSpacing: "0.04em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  subtitle1: {
    fontSize: "16px",
    fontWeight: 400,
    lineHeight: 1.75,
    letterSpacing: "0.04em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  body1: {
    fontSize: "16px",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: "0.005em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  body2: {
    fontSize: "14px",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: "0.0025em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  body3: {
    fontSize: "12px",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: "0.0025em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  subtitle2: {
    fontFamily: "Noto Sans JP",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "175%",
    letterSpacing: "0.56px",
  },
  caption: {
    fontSize: "12px",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: "0.0125em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  overline: {
    fontSize: "10px",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: "0.015em",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  staffyChat: {
    color: "rgba(0, 0, 0, 0.87)",
    textAlign: "justify",
    fontFeatureSettings: "'pwid' on",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
    letterSpacing: "0.03px",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  userChat: {
    color: "var(--white, #FFF)",
    textAlign: "justify",
    fontFeatureSettings: "'pwid' on",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
    letterSpacing: "0.03px",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  chatHeaderText: {
    color: "#6D3588",
    fontSize: "16px",
    fontWeight: 700,
    lineHeight: "24px",
    letterSpacing: "0.64px",
    wordBreak: "break-word",
    fontFamily: "Noto Sans JP, sans-serif",
  },
  homeBoxText: {
    fontFamily: "Noto Sans JP",
    fontWeight: "400",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0.08px",
  },
};
